### ISSUE TITLE
xAPI response case should be lower case

### ISSUE THREAD

**Issue by garemoko** [h5p/h5p-true-false#4]
The case of the correctResponsePattern and response should be lowercase i.e. "true" instead of "True".

**Comment by fnoks** [comment]
Could you explain why you it should be lowercase? In this content type, it is possible for the author to label them as something else, e.g "Correct" & "Wrong", "Yes" & "No" and so on.

**Comment by garemoko** [comment]
The xAPI spec requires the response to be 'true' or 'false' so the data is standardised to make it easier for systems reading the data. In theory any other value could be rejected by LRS validation (although many LRSs don't go to that level of detail in validation).

See https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#response-patterns

**Comment by fnoks** [comment]
I see - thanks for clarifying. Do you still think this should be of interactionType 'true-false' when the options presented to the user may be something else? The author could e.g. name the two options 'Red' and 'Blue'. Even if this content type ios meant to be used for true-false questions, maybe it is more correct to use the interactionType 'choice'?

**Comment by garemoko** [comment]
In the case of red-blue then yes the choice makes more sense, however since the interaction type is called true-false I think anybody naming the options red/blue is asking for trouble. 

I would keep it as a true/false question because systems representing the data in reports could have a special visualisation specifically for true/false questions and it would be a shame to miss out on that in order to support edge cases of people abusing the question type. 

That said, Watershed treats true/false questions exactly the same as choice questions when it comes to visualizations and I'm not away of any other reporting tool that treats them differently.

**Comment by fnoks** [comment]
I agree, this is built to be a TrueFalse-type. We will keep the interactionType as is, and fix the correctResponsePattern to follow the spec:
https://h5ptechnology.atlassian.net/browse/HFP-432

**Comment by tajakobsen** [comment]
Fix has been applied to the content type, and will be included in the next release. See [Jira](https://h5ptechnology.atlassian.net/browse/HFP-432) for more info.

**Comment by fnoks** [comment]
This is now released!
